# Generated by Django 4.0.1 on 2022-01-14 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='userMame',
            new_name='userName',
        ),
    ]
