# Generated by Django 4.0.1 on 2022-01-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_rename_useremail_homepage_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
