# Generated by Django 4.0.1 on 2022-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testApp', '0004_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(default=' ', max_length=200)),
                ('profilePic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
