# Generated by Django 4.0.1 on 2022-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_alter_userprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
