# Generated by Django 4.0.1 on 2022-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_userprofile_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
