# Generated by Django 4.0.1 on 2022-01-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_remove_worlddata_city_remove_worlddata_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorldData',
        ),
    ]
