# Generated by Django 4.0.1 on 2022-01-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_city_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testApp.state'),
        ),
        migrations.AddField(
            model_name='state',
            name='stateID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='testApp.country'),
        ),
    ]
