# Generated by Django 4.0.1 on 2022-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_city_cityid_state_stateid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityID',
            new_name='stateID',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='stateID',
            new_name='countryID',
        ),
    ]
